### ISSUE TITLE
Boykott etwas zu rabiat bei Tagesschau

### ISSUE THREAD

**Issue by Oi-sin** [trych/wm-boykott#1]
Auf https://www.tagesschau.de/allemeldungen/ wird etwas zu rabiat blockiert: hier verschwinden alle Meldungen.

Lösungsvorschlag: entweder gar nichts blockieren oder nur die Meldungen zur WM 

Browser: Vivaldi 5.6.2839.3 (Offizieller Build) (64-Bit)

**Comment by trych** [comment]
Danke für den Hinweis, auf der Seite schlägt das Filtersystem tatsächlich fehl, weil irgenwie der ganze Newsticker-Block die Klasse `teaser` bekommt und sobald dann irgendwelche WM-Meldungen auftauchen wird alles ausgeblendet. Ich schau mal, ob ich eine gute Lösung finde.

**Comment by trych** [comment]
Ist jetzt in v1.0.3 behoben. Als Firefox-Addon schon verfügbar, die Chrome-Extension musst du weiterhin hier auf GitHub als .zip runterladen. (Ich weiß nicht, welche Extension Vivaldi benötigt)

**Comment by Oi-sin** [comment]
Super. Vielen Dank. 👍

Zur Info: Vivaldi basiert auf Chromium. Chrome-Erweiterungen laufen da bisher alle ohne Probleme.
