### ISSUE TITLE
SZ: Nicht alle WM-Artikel werden gefiltert

### ISSUE THREAD

**Issue by PhilLecl** [trych/wm-boykott#2]
Aktuell werden zwei Artikel auf sueddeutsche.de nicht gefiltert, wahrscheinlich weil sie keine der üblichen Keywords in der Kurzzusammenfassung haben:

![grafik](https://user-images.githubusercontent.com/54592274/203871034-1b60f7ec-d03c-48d3-a191-b73d7792b81f.png)

Würde vorschlagen, zumindest "Bundestrainer" in die Keywords aufzunehmen.

Interessant wäre vielleicht auch eine RegEx, die Spielergebnisse erkennt (\d:\d oder so).
Könnte allerdings zu aggressiv sein, vielleicht könnte man Einstellungen hinzufügen, um das aktivieren/deaktivieren zu können.

**Comment by trych** [comment]
Danke für den Hinweis. Habe jetzt "Bundestrainer" und "Flick" mal bei den Schlagwörtern hinzugefügt. Bei dem Portugalartikel sehe ich tatsächlich keinen sinnvollen Ansatzpunkt. Finde ich aber journalistisch auch fast ein bisschen unsauber gearbeitet, dass da nicht in der Dachzeile zumindest mal WM erwähnt ist oder so.

Einstellungen stehen grundsätzlich auf der ToDo-Liste, ob ich da diese WM noch die Zeit für finde, weiß ich allerdings nicht ganz genau.

**Comment by trych** [comment]
Neue Keywords sind jetzt in v1.0.3 hinzugefügt. Als Firefox-Addon schon verfügbar, die Chrome-Extension musst du weiterhin hier auf GitHub als .zip runterladen.
